{"timestamp": "2025-08-27T15:57:38.730634", "level": "INFO", "message": "\u001b[2m2025-08-27T07:57:38.730634Z\u001b[0m [\u001b[32m\u001b[1minfo     \u001b[0m] \u001b[1mlogging_initialized           \u001b[0m [\u001b[0m\u001b[1m\u001b[34mapp.core.logger_utils\u001b[0m]\u001b[0m \u001b[36menvironment\u001b[0m=\u001b[35mdevelopment\u001b[0m \u001b[36mfilename\u001b[0m=\u001b[35mlogger_utils.py\u001b[0m \u001b[36mfunc_name\u001b[0m=\u001b[35m<module>\u001b[0m \u001b[36mlineno\u001b[0m=\u001b[35m185\u001b[0m \u001b[36mlog_format\u001b[0m=\u001b[35mconsole\u001b[0m \u001b[36mlog_level\u001b[0m=\u001b[35mDEBUG\u001b[0m \u001b[36mmodule\u001b[0m=\u001b[35mlogger_utils\u001b[0m \u001b[36mpathname\u001b[0m=\u001b[35mD:\\rag_minirag\\MiniCascade-RAG\\app\\core\\logger_utils.py\u001b[0m", "module": "logger_utils", "function": "<module>", "filename": "D:\\rag_minirag\\MiniCascade-RAG\\app\\core\\logger_utils.py", "line": 185, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.752780", "level": "DEBUG", "message": "{\"message\": \"Starting topology monitoring\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.753943", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"previousDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: Unknown, servers: []>\", \"newDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.755172", "level": "DEBUG", "message": "{\"message\": \"Starting server monitoring\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo2\", \"serverPort\": 30002}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.755718", "level": "DEBUG", "message": "{\"message\": \"Starting server monitoring\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo1\", \"serverPort\": 30001}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.756318", "level": "DEBUG", "message": "{\"message\": \"Starting server monitoring\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo3\", \"serverPort\": 30003}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.758583", "level": "DEBUG", "message": "{\"message\": \"Connection pool created\", \"clientId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo2\", \"serverPort\": 30002}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.760393", "level": "DEBUG", "message": "{\"message\": \"Connection pool created\", \"clientId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo1\", \"serverPort\": 30001}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:38.763439", "level": "DEBUG", "message": "{\"message\": \"Connection pool created\", \"clientId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo3\", \"serverPort\": 30003}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:41.493790", "level": "DEBUG", "message": "{\"message\": \"Server heartbeat failed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo3\", \"serverPort\": 30003, \"awaited\": false, \"durationMS\": 2735.000000000582, \"failure\": \"\\\"AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:41.494390", "level": "DEBUG", "message": "{\"message\": \"Server heartbeat failed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo2\", \"serverPort\": 30002, \"awaited\": false, \"durationMS\": 2735.000000000582, \"failure\": \"\\\"AutoReconnect('mongo2:30002: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:41.494390", "level": "DEBUG", "message": "{\"message\": \"Server heartbeat failed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"serverHost\": \"mongo1\", \"serverPort\": 30001, \"awaited\": false, \"durationMS\": 2735.000000000582, \"failure\": \"\\\"AutoReconnect('mongo1:30001: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:41.496183", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"previousDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None>]>\", \"newDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:41.500336", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"previousDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None, error=AutoReconnect('mongo2:30002: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T15:57:41.512598", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aeba72d1d148314d537afa\"}, \"previousDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None, error=AutoReconnect('mongo2:30002: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 68aeba72d1d148314d537afa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None, error=AutoReconnect('mongo1:30001: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None, error=AutoReconnect('mongo2:30002: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.571915", "level": "INFO", "message": "\u001b[2m2025-08-27T08:00:26.571915Z\u001b[0m [\u001b[32m\u001b[1minfo     \u001b[0m] \u001b[1mlogging_initialized           \u001b[0m [\u001b[0m\u001b[1m\u001b[34mapp.core.logger_utils\u001b[0m]\u001b[0m \u001b[36menvironment\u001b[0m=\u001b[35mdevelopment\u001b[0m \u001b[36mfilename\u001b[0m=\u001b[35mlogger_utils.py\u001b[0m \u001b[36mfunc_name\u001b[0m=\u001b[35m<module>\u001b[0m \u001b[36mlineno\u001b[0m=\u001b[35m185\u001b[0m \u001b[36mlog_format\u001b[0m=\u001b[35mconsole\u001b[0m \u001b[36mlog_level\u001b[0m=\u001b[35mDEBUG\u001b[0m \u001b[36mmodule\u001b[0m=\u001b[35mlogger_utils\u001b[0m \u001b[36mpathname\u001b[0m=\u001b[35mD:\\rag_minirag\\MiniCascade-RAG\\app\\core\\logger_utils.py\u001b[0m", "module": "logger_utils", "function": "<module>", "filename": "D:\\rag_minirag\\MiniCascade-RAG\\app\\core\\logger_utils.py", "line": 185, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.584786", "level": "DEBUG", "message": "{\"message\": \"Starting topology monitoring\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.587282", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"previousDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: Unknown, servers: []>\", \"newDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.590218", "level": "DEBUG", "message": "{\"message\": \"Starting server monitoring\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo2\", \"serverPort\": 30002}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.591311", "level": "DEBUG", "message": "{\"message\": \"Starting server monitoring\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo3\", \"serverPort\": 30003}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.592412", "level": "DEBUG", "message": "{\"message\": \"Starting server monitoring\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo1\", \"serverPort\": 30001}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.595217", "level": "DEBUG", "message": "{\"message\": \"Connection pool created\", \"clientId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo2\", \"serverPort\": 30002}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.600024", "level": "DEBUG", "message": "{\"message\": \"Connection pool created\", \"clientId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo3\", \"serverPort\": 30003}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:26.610295", "level": "DEBUG", "message": "{\"message\": \"Connection pool created\", \"clientId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo1\", \"serverPort\": 30001}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:29.353296", "level": "DEBUG", "message": "{\"message\": \"Server heartbeat failed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo3\", \"serverPort\": 30003, \"awaited\": false, \"durationMS\": 2750.0, \"failure\": \"\\\"AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:29.353296", "level": "DEBUG", "message": "{\"message\": \"Server heartbeat failed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo1\", \"serverPort\": 30001, \"awaited\": false, \"durationMS\": 2734.0000000003783, \"failure\": \"\\\"AutoReconnect('mongo1:30001: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:29.354036", "level": "DEBUG", "message": "{\"message\": \"Server heartbeat failed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"serverHost\": \"mongo2\", \"serverPort\": 30002, \"awaited\": false, \"durationMS\": 2750.0, \"failure\": \"\\\"AutoReconnect('mongo2:30002: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:29.355184", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"previousDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None>]>\", \"newDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:29.360452", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"previousDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None, error=AutoReconnect('mongo1:30001: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
{"timestamp": "2025-08-27T16:00:29.362063", "level": "DEBUG", "message": "{\"message\": \"Topology description changed\", \"topologyId\": {\"$oid\": \"68aebb1a4be9783e0e7527f3\"}, \"previousDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None, error=AutoReconnect('mongo1:30001: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 68aebb1a4be9783e0e7527f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None, error=AutoReconnect('mongo1:30001: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None, error=AutoReconnect('mongo2:30002: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\"}", "module": "logger", "function": "_debug_log", "filename": "D:\\test_suit\\conda\\Lib\\site-packages\\pymongo\\logger.py", "line": 108, "environment": "development"}
